database:
  server: brownwong.database.windows.net
  port: 1433
  name: "MyAIProject"
  username: "weishenwong80"
  password: "xiaLAN1980"
  driver: "ODBC Driver 18 for SQL Server"
  encrypt: true
  trust_server_certificate: false
  connection_timeout: 30
